[project]
name = "exe-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jin", email = "jhjin0306@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
]

[project.scripts]
exe-3 = "exe_3:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
